### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by monalisa62003** [LuminatedSparkles/IceCrownMedia#1]
Hi i don't know if this is serious or not but why don't you learn to code, ive been trying to for years and its really difficult but you do get the hang of it. Do you know anyone irl who codes i get my brother to help me but there are tones of tutorials. Its all about trial and error

**Comment by LuminatedSparkles** [comment]
Because I can't, it's to much and I may learn fast, but that coding is to
much for me in that way and I don't want to do that. I have a lot of other
stuff around my head, even if I sit mostly on my ass right now, but the
codes are a other view there, and is really to much for me as woman.

Nice Greetings

**Comment by monalisa62003** [comment]
If i can do it anyone can🤣youd be amazed how crap my life is. Im using my phone for it a lot, in bed right now! 
 Its all about trial and error. You copy a code and change the wording, thats all about it really.
